services:
  jupyter:
    container_name: "tensorflow-notebook"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./demo:/tf/demo
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DISABLE_REQUIRE=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
